---
- name: Configure App
  hosts: app
  become: true
  vars:
    db_host: 84.252.128.148
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      when: "ansible_service_mgr == 'systemd'"
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu

    - name: enable puma
      command: systemctl enable puma
  handlers:
    - name: reload puma
      systemd:
        name: puma
        state: reloaded
        daemon_reload: yes
